env: "local"
grpc:
  port: 44044
  timeout: 10h
db:
  host: localhost
  port: 3306
  user: user
  name: tasks
  password: password
  max_open_connections: 10
  max_idle_connections: 5
  max_lifetime: 60
