postgres:
  host: postgres
  user: user
  name: auth
  password: password
grpc:
  port: 44046
  timeout: 10h
redis:
  port: 6379
  host: localhost
  ttl: 24h
jwt:
  accessTTL: 900s
  refreshTTL: 90 # days
kafka:
  brokers:
    - kafka:29092
  producer:
    retryMax: 5
    flushTimeout: 500ms
    batchSize: 100
    compression: snappy