postgres:
  host: localhost
  user: user
  name: postgres
  password: password
grpc:
  port: 44044
  timeout: 10h
redis:
  port: 44044
  host: localhost
  ttl: 24h
jwt:
  accessTTL: 20s
  refreshTTL: 90 # days