env: "local"
grpc:
  port: 44048
  timeout: 10h
db:
  host: postgres
  port: 3306
  user: user
  name: user
  password: password
  max_open_connections: 10
  max_idle_connections: 5
  max_lifetime: 60
kafka:
  brokers:
    - kafka:29092

  producer:
    retryMax: 5
    flushTimeout: 500ms
    batchSize: 100
    compression: snappy
clients:
  userClientAddr: "user-service:44044"
  teamClientAddr: "team-service:44045"
  clientTimeout: 30s