services:
  user-migrate:
    build:
      context: ../services/user-service
      dockerfile: ../../local-docker/dockerfiles/user.dockerfile
    command: [ "./migrate" ]
    env_file:
      - .env.example
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:50051" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
  team-migrate:
    build:
      context: ../services/team-service
      dockerfile: ../../local-docker/dockerfiles/team.dockerfile
    command: [ "./migrate" ]
    env_file:
      - .env.example
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:50051" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
  board-migrate:
    build:
      context: ../services/board-service
      dockerfile: ../../local-docker/dockerfiles/board.dockerfile
    command: [ "./migrate" ]
    env_file:
      - .env.example
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=localhost:50051" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
networks:
  backend:
    external: true